### PR TITLE
[I18N] payment_mollie_official: add Dutch translation strings

### PR DESCRIPTION
**Pull request by Yenthe666**
This PR adds the Dutch translations for the `payment_mollie_official` module in V10.

### CODE REVIEW

**Comment by Yenthe666** [comment]
@Smitsel I see you approved the other PR's, can you add this in too please?

**Comment by Yenthe666** [comment]
CC @willemstuursma & @jeanpaulrobineau & @huysmki

**Comment by Smitsel** [comment]
Hi @Yenthe666, ill have a look today. Sorry for the delay!

**Comment by Yenthe666** [comment]
That is awesome, thanks a lot!
P.S: Will a PR be accepted to improve things in the 10.0 module too?

**Comment by Smitsel** [comment]
Yes those will be much appreciated. I will have to pass this PR to @huysmki as he is the odoo developer.

**Comment by Yenthe666** [comment]
Okay, thanks.

**Comment by huysmki** [comment]
Merged

**Comment by Yenthe666** [comment]
Yikes thanks guys.
A few things that could be done too:
- Forward translations to 11.0
- Do correct imports of Python files in the `10.0` module (`from . import x` instead of `import x`)
- Better handle failing of transactions.

**Comment by Smitsel** [comment]
Hey @Yenthe666,

Thanks for the feedback. PRs are highly appreciated!

**Comment by Yenthe666** [comment]
Made one for the model files at https://github.com/mollie/mollie-odoo/pull/9
If I have more time somewhere along the line I'll do the translations / better handle failures. No promisses 😉

**Pull request merged**
